appUrl : http://localhost:8080/          # your application  url

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: -----------------------------------YOUR_CLIENT_ID
            client-secret: --------------------------------YOUR_CLIENT_SECRET
            redirect-uri: "${appUrl}/login/oauth2/code/google"          # your redirect url
            scope:
              - openid
              - profile
              - email
            client-name: Google
